# Generated by Django 5.2.1 on 2025-05-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categor_name',
            new_name='category_name',
        ),
    ]
